---
- block:
    - name: Down cases container
      docker_compose:
        project_src: /srv/cases
        files: '{{ _files|list }}'
        state: absent
        remove_volumes: '{{ "no" if _persistent else "yes" }}'
      environment:
        NETWORK: '{{ _network }}'
  tags: [cases]
