---
- block:
    - name: Down proxy container
      docker_compose:
        project_src: /srv/proxy
        files: '{{ _files|list }}'
        state: absent
        remove_volumes: '{{ "no" if _persistent else "yes" }}'
  tags: [proxy]
