---
- block:
    - name: Stop discovery container
      docker_compose:
        project_src: /srv/discovery
        files: '{{ _files|list }}'
        state: present
        stopped: yes
      environment:
        NETWORK: '{{ _network }}'
  tags: [discovery]
