---
formio:
  enabled: true
  order: -10
  repository: https://github.com/MazdaPower/Formio.git
  version: develop
  api:
    host: api.formio.dev.ds
    admin:
      user: admin@staff.ds
      password: admin
  database:
    ui:
      host: ui.database.formio.dev.ds
  docker:
    - docker-compose.yml
    - docker-compose.dev.yml
    - /root/docker/formio/docker-compose.yml
    - /root/docker/formio/docker-compose.dev.yml
