---
- block:
    - name: Stop cases container
      docker_compose:
        project_src: /srv/cases
        files: '{{ _files|list }}'
        state: present
        stopped: yes
      environment:
        NETWORK: '{{ _network }}'
        PROXY_HOST: '{{ _proxy_host }}'
  tags: [cases]
