---
- block:
    - name: Down cms container
      docker_compose:
        project_src: /srv/cms
        files: '{{ _files|list }}'
        state: absent
        remove_volumes: '{{ "no" if _persistent else "yes" }}'
      environment:
        NETWORK: '{{ _network }}'
  tags: [cms]
